version: '3.3'

services:

  taskmanager:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    image: taskmanager
    container_name: taskmanager
    restart: on-failure
    environment:
      - GUNICORN_WORKERS=1
      - TASK_REPOSITORY_TYPE=sqlite
      - SQL_SERVER=sqlite
      - SQL_DATABASE=tasmanager_test.db
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}/..:/credentials
    ports:
      - 8080:4000
