version: '3.3'

services:

  taskmanager:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    image: taskmanager
    container_name: taskmanager
    restart: on-failure
    environment:
      - GUNICORN_WORKERS
      - TASK_REPOSITORY_TYPE
      - SQL_SERVER
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}/..:/credentials
    ports:
      - 8080:4000
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
