version: '3.3'

services:

  taskmanager:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    image: taskmanager
    container_name: taskmanager
    restart: on-failure
    environment:
      - EVENT_PUBLISHER_TYPE
      - EVENT_SUBSCRIBER_TYPE
      - RABBITMQ_HOST
      - GUNICORN_WORKERS
      - TASK_REPOSITORY_TYPE
      - EVENT_REPOSITORY_TYPE
      - SQL_SERVER
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_PORT
    ports:
      - 8080:4000
    depends_on:
      - rabbitmq
      - mysql
    links:
      - rabbitmq
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-taskmanager
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysql", "--user=$$MYSQL_USER", "--password=$$MYSQL_ROOT_PASSWORD", "-e", "'SHOW DATABASES;'"]
      interval: 30s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer-taskmanager
    depends_on:
      - mysql
    restart: always
    ports:
      - 8090:8080

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-taskmanager
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
