version: '3.3'

services:

  taskmanager:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    image: taskmanager
    container_name: taskmanager
    restart: on-failure
    environment:
      - GUNICORN_WORKERS
      - TASK_REPOSITORY_TYPE
      - SQL_SERVER
      - SQL_DATABASE
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}/..:/credentials
    ports:
      - 8080:4000
